[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 240000000L
board_build.partitions = min_spiffs.csv

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    mikalhart/TinyGPSPlus @ ^1.0.3
    electroniccats/MPU6050 @ ^0.6.0

build_flags =
    -D CORE_DEBUG_LEVEL=3
